
---
- hosts: 34.239.183.77
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: install apache package
    apt:
      name: apache2
      state: absent

  - name: add php support for apache 
    apt:
      name: libapache2-mod-php
      state: absent


    