---
- hosts: all
  become: true
  tasks:

    - name: install updates (RedHat)
      tags: always
      package:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "RedHat"

    - name: install updates (Ubuntu)
      tags: always
      package:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"


- hosts: ubuntu
  become: true
  tasks:

    - name: install apache and php for Ubuntu servers
      tags: apache,apache2,ubuntu
      package:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: redhat
  become: true
  tasks:

    - name: install apache and php for RedHat servers
      tags: apache,httpd,redhat
      package:
        name:
          - httpd
          - php
        state: latest
        update_cache: yes
      when: ansible_distribution == "RedHat"

    - name: copy default html
      tags: apache,apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
