---
- hosts: all
  become: true
  tasks:
    - name: updates (RedHat)
      tags: always
      package:
        update_cache: yes
        changed_when: false
      when: ansible_distribution == "RedHat"

    - name: updates (Ubuntu)
      tags: always
      package:
        update_cache: yes
        changed_when: false
      when: ansible_distribution == "Ubuntu"

- hosts: ubuntu
  become: true
  tasks:
    - name: install apache and php for Ubuntu servers
      tags: apache,apache2,ubuntu
      package:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: redhat
  become: true
  tasks:
    - name: install apache and php for RedHat servers
      tags: apache,httpd,redhat
      package:
        name:
          - httpd
          - php
        state: latest
        update_cache: yes
      when: ansible_distribution == "RedHat"

    - name: start httpd on RedHat
      tags: apache,httpd,redhat
      lineinfile: 
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin'
        line: ServerAdmin roote@localhost
      when: ansible_distribution == "RedHat"
      register: httpd

    - name: restart httpd on RedHat
      tags: apache,httpd,redhat
      service:
        name: httpd
        state: restarted
      when: httpd.changed

    - name: change e-mail address for admin
      tags: apache,apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

    - name: copy default html
      tags: apache,apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

- hosts: all
  become: true
  tasks:

    - name: add ssh key for simone
      tags: always
      authorized_key: 
        user: simone
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJd+tJVepiMtwvlE5r6dC/SexvEsU2tKBHINs4k8WSaJ ansible"


