    - name: updates (Ubuntu)
      tags: always
      package:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: install apache and php for Ubuntu servers
      tags: apache,apache2,ubuntu
      package:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
