    - name: add ssh key for simone
      tags: always
      authorized_key: 
        user: simone
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJd+tJVepiMtwvlE5r6dC/SexvEsU2tKBHINs4k8WSaJ ansible"

    - name: change e-mail address for admin
      tags: apache,apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

    - name: copy default html
      tags: apache,apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
